// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace WebApiUebungen.Entities
{
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductNr { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string CreatorUsername { get; set; }
    }
}